import numpy, argparse, pandas, scipy
from helpers import helpers

def parse_pair(s):
    return [float(x) for x in s.split(',')]

parser = argparse.ArgumentParser()
parser.add_argument("--input_file", type=str, help="parquet file generated by variable_creation.py")
parser.add_argument("--output_file", type=str, help="name of output file, with path.")
parser.add_argument("--variable", type=str, help="variable to compute")
parser.add_argument('--region', type=parse_pair, required=True,help='An integration region denoted as shallow,deep.')
parser.add_argument("--pressure_buffer", type=float, nargs='?', const=100.0, default=100.0, help="pressure range to keep on either side of the pressure ROI")
parser.add_argument("--pressure_index_buffer", type=int, nargs='?', const=5, default=5, help="minimum number of elements to preserve in the pressure buffer margins")
args = parser.parse_args()

df = pandas.read_parquet(args.input_file, engine='pyarrow')

# create a dense comb for trapezoidal integration
pressure_comb = helpers.integration_comb(args.region)

# interpolate to comb
df[[args.variable, 'flag']] = df.apply(
    lambda row: pandas.Series(helpers.interpolate_to_levels(row, args.variable, pressure_comb)),
    axis=1
)

df['pressure'] = df.apply(
    lambda row: pressure_comb,
    axis=1
)

# integrate over region
df[args.variable+'_integration'] = df.apply(
    lambda row: helpers.integration_regions([args.region], row['pressure'], row[args.variable]),
    axis=1
)

# combs can be huge, drop them.
df = df.drop(columns=[args.variable, 'pressure'])

# dump any rows that failed to integrate
df = df[~df[args.variable+'_integration'].apply(lambda x: numpy.isnan(x[0]) )].reset_index(drop=True)

df.to_parquet(args.output_file, engine='pyarrow')
