## see helpers/helpers.py for warning flag table
import numpy, argparse, pandas, scipy, os
from helpers import helpers

def parse_pair(s):
    if s is 'None':
        return None
    return [float(x) for x in s.split(',')]

parser = argparse.ArgumentParser()
parser.add_argument("--input_file", type=str, help="parquet file generated by variable_creation.py")
parser.add_argument("--output_file", type=str, help="name of output file, with path.")
parser.add_argument("--pscale", type=float, default=1.0, help="scale factor to multiply pressure by; default 1 (ie dbar), set to 10000 for Pa")
parser.add_argument("--variable", type=str, help="variable to integrate")
parser.add_argument('--region', type=parse_pair,help='An integration region denoted as shallow,deep. If absent, integration is perfomed over the entire profile.')

args = parser.parse_args()

df = pandas.read_parquet(args.input_file, engine='pyarrow')

# temperatures should be in kelvin before integration
variable = args.variable
if variable in ['temperature', 'conservative_temperature', 'potential_temperature']:
    df[variable] = df[variable] + 273.15

if args.region is not None:
    # create a dense comb for trapezoidal integration
    pressure_comb = helpers.integration_comb(args.region)*args.pscale

    # interpolate to comb
    df[[variable+'_comb', 'flag']] = df.apply(
        lambda row: pandas.Series(helpers.interpolate_to_levels(row, variable, pressure_comb)),
        axis=1
    )

    # integrate over region
    df[variable+'_integration'] = df.apply(
        lambda row: helpers.integration_region(args.region, pressure_comb, row[variable+'_comb']),
        axis=1
    )

    # combs can be huge, drop them.
    df = df.drop(columns=[variable+'_comb'])
else:
    # integrate over entire profile
    df[variable+'_integration'] = df.apply(
        lambda row: helpers.integration_region([row['pressure'][0], row['pressure'][-1]], row['pressure']*args.pscale, row[variable]),
        axis=1
    )

# dump any rows that failed to integrate
rejects = df[df[variable+'_integration'].apply(lambda x: numpy.isnan(x[0]) )].reset_index(drop=True)
rejects = rejects[['float', 'cycle', 'longitude', 'latitude', 'juld', 'flag']]
df = df[~df[variable+'_integration'].apply(lambda x: numpy.isnan(x[0]) )].reset_index(drop=True)

rejects.to_parquet(os.path.join(args.output_file.split('.')[0] + '_rejects.parquet'), engine='pyarrow')
df.to_parquet(args.output_file, engine='pyarrow')
