## see helpers/helpers.py for warning flag table
import numpy, argparse, pandas, scipy, os
from helpers import helpers

# argument setup
def parse_list(s):
    return [str(x) for x in s.split(',')]

def float_list(s):
    if s == 'None':
        return None
    return [float(x) for x in s.split(',')]

parser = argparse.ArgumentParser()
parser.add_argument("--input_file", type=str, help="parquet file generated by variable_creation.py")
parser.add_argument("--output_file", type=str, help="name of output file, with path.")
parser.add_argument("--variables", type=parse_list, help="variables to interpolate, csv-delimited")
parser.add_argument("--pressure_range", type=float_list, help="min,max pressure range, CSV.")
parser.add_argument('--spacing', type=float, default=0.2, help="the spacing in dbar to interpolate to; default is 0.2 dbar; specify along with pressure_range; only specify one of spacing or level_set")
parser.add_argument('--level_set', type=float_list, help="the specific levels in dbar to interpolate to, csv-delimited; only specify one of spacing or level_set")
parser.add_argument('--purge_fails', type=bool, default=False, help="whether to drop profiles that fail to interpolate to any levels for all of the specified variabled; default is False")
args = parser.parse_args()

# bonus marks for good behavior
if (args.spacing is None) and (args.level_set is None):
    raise ValueError('Specify level_set OR each of pressure_range, spacing.')
if (args.spacing is not None) and (args.level_set is not None):
    raise ValueError('Only one of spacing or level_set should be specified. Use spacing for a regular comb, or level_set for custom levels.')
if (args.spacing is not None) and (args.pressure_range is None):
    raise ValueError('When using spacing, pressure_range must also be specified.')

# figure out our level set:
level_set = []
if args.level_set is not None:
    level_set = args.level_set
else:
    level_set = numpy.arange(args.pressure_range[0], args.pressure_range[1] + args.spacing, args.spacing)

# load data
df = pandas.read_parquet(args.input_file, engine='pyarrow')

# interpolate requested variables to levels
for var in args.variables:
    df[[var, 'flag']] = df.apply(
        lambda row: pandas.Series(helpers.interpolate_to_levels(row, var, level_set)),
        axis=1
    )

# set pressures to the level set
df['pressure'] = df.apply(
    lambda row: level_set,
    axis=1
)

# if purge_fails is set, drop any profiles that failed to interpolate to any levels for all of the specified variables
if args.purge_fails:
    rejects = df[df.apply(lambda row: all([numpy.isnan(row[var]).all() for var in args.variables]), axis=1)].reset_index(drop=True)
    rejects = rejects[['float', 'cycle', 'longitude', 'latitude', 'juld', 'flag']]
    rejects.to_parquet(os.path.join(args.output_file.split('.')[0] + '_rejects.parquet'), engine='pyarrow')
    df = df[~df.apply(lambda row: all([numpy.isnan(row[var]).all() for var in args.variables]), axis=1)].reset_index(drop=True)

df.to_parquet(args.output_file, engine='pyarrow')

