import numpy, argparse, glob, pandas, gsw
from helpers import helpers

# argument setup 
parser = argparse.ArgumentParser()
parser.add_argument("--input_file", type=str, help="parquet file generated by qc_filter.py")
parser.add_argument("--absolute_salinity", type=bool, default=True, help="compute and store absolute salinity")
parser.add_argument("--potential_temperature", type=bool, default=True, help="compute and store potential temperature")
parser.add_argument("--conservative_temperature", type=bool, default=True, help="compute and store conservative temperature")
args = parser.parse_args()

df = pandas.read_parquet(args.input_file, engine='pyarrow')

if args.absolute_salinity or args.potential_temperature or args.conservative_temperature:
    df['absolute_salinity'] = df.apply(
        lambda row: gsw.conversions.SA_from_SP(
            row['salinity'], row['pressure'], row['longitude'], row['latitude']
        ),
        axis=1
    )

if args.potential_temperature:
    df['potential_temperature'] = df.apply(
        lambda row: gsw.conversions.pt0_from_t(
            row['absolute_salinity'], row['temperature'], row['pressure']
        ),
        axis=1
    )
    df['potential_temperature'] = df['potential_temperature'] + 273.15

if args.conservative_temperature:
    df['conservative_temperature'] = df.apply(
        lambda row: gsw.conversions.CT_from_t(
            row['absolute_salinity'], row['temperature'], row['pressure']
        ),
        axis=1
    )
    df['conservative_temperature'] = df['conservative_temperature'] + 273.15

df.to_parquet(f"{args.input_file.split('.')[0]}_derived.parquet", engine='pyarrow')